### ISSUE TITLE
Finalizar modelo de Cohort

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/models#2]
- [x] **Resolver issue con _id_/_slug_**. Esto básicamente hace referencia a los problemas que hemos ido encontrando con el formato de los _ids_ que actualmente usamos para los documentos de la colección de cohorts (por ejemplo: `lim-2018-11-bc-core-am`). El uso de estos _ids semánticos_ hace muy difícil _cambiar_ información sobre el cohort ya que esto implica cambiar _id_, el cual está almacenado en un montón de otras colecciones que hacen referencia a estos objetos.
- [x] **Agegar propiedad `rubric`**. De acuerdo a lo conversado en https://github.com/Laboratoria/api.laboratoria.la/issues/86, necesitamos asociar a cada _cohort_ con una versión de la _rúbrica_.
- [x] **Agregar propiedad `generation`**. Se propone agregar una propiedad que represente lo que coloquialmente usan tanto nuestro equipo como estudiantes y egresadas: por ejemplo, la _octava generación de Lima_, la _sexta generación de CDMX_ o la _segunda generación de GDL_, ... La propuesta es que esta propiedad tenga un valor por defecto (autocomputado basado en el valor de la última generación para la sede en cuestión), y que se valide para garantizar que no hay duplicados por sede. Esto nos ayudaría a _expresar_ la data de cohorts en un leguage más familiar para todxs.
- [ ] cohort users?
- [ ] cohort courses?
- [ ] cohort projects?
- [ ] usersCount

**Comment by lupomontero** [comment]
* **`id`/`slug`**: Esta propiedad se considerará como _deprecated/legacy_ desde el principio y contendrá el id del cohort en firestore si es que alguna vez existió ahí.

* **Agegar propiedad `rubric`**: Hemos decidido guardar un string con un número, haciendo referencia a la serie (versión mayor) de la rúbrica. Esto significa que los projectos asignados al cohort pueden haber sido parseados con diferentes versiones de la rúbrica, pero todas deben compartir el número de versión _mayor_. Por ejemplo, si el cohort especifica la versión `2` de la rúbrica, podríamos tener proyectos parseados con las versiones `2.0.1`, `2.0.2` o `2.4.1` de la rúbrica.

* **Agregar propiedad `generation`**: Hemos dicidido agregar esto como un número entero que se auto incrementará por _campus_ cada vez que se cree un cohort de admisión. Para los demás tipos de cohort se validará que la generación exista.

***

Todavía falta:

- [ ] cohort users?
- [ ] cohort courses?
- [ ] cohort projects?
- [ ] usersCount

**Comment by corosteg** [comment]
Por favor relacionar ese issues con ese proyecto:
https://github.com/Laboratoria/lms.laboratoria.la/projects/4

@lupomontero

**Comment by lupomontero** [comment]
UPDATE:

* Con respecto a `cohorts/:cohortid/users`, se ha decidido manejar esto como una colección separada de objetos _cohort membership_ (wip). De esta forma evitamos "duplicar" esta data en una subcolección de los perfiles de usuarios (como hacemos en Firestore). Por otro lado, en algunos cohorts (por ejemplo selección) pueden haber miles de usuarios asignados a un cohort, y no queremos impactar dramáticamente el tamaño del objeto cohort. Además estos objetos se escriben cada vez que una candidata postula al bootcamp y no queremos tener que actualizar el objeto cohort entero cada vez que se agregue (o borre) una estudiante de un cohort (limitando la concurrencia).
* Por otro lado, `cohorts/:cohortid/courses` y `cohorts/:cohortid/projects` se mantendrán dentro del objeto `Cohort` ya que siempre son pocos elementos (menos de 10), con lo cual no afectan drásticamente al _tamaño_ de los objetos `Cohort`, además estos campos no se escriben con mucha frecuencia ni con mucha concurrencia, solo se suelen _escribir_ justo después de crear el cohort y solo escriben los admins del cohort (coaches y/o training managers).
* La subcolección `cohorts/:cohortid/courses` pasa a ser la propiedad `topics` en los objeto de tipo `Cohort` para alinearse con la terminología usada en la currícula.

Espero mandar un PR al final del día tanto en este repo como en `Laboratoria/schemas`.

cc/ @Xpktro @FabianBravoA @bouli
